### ISSUE TITLE
Project TODO list

### ISSUE THREAD

**Issue by Titoongh** [1hake/gpt-siri#2]
- [ ] Stocker tous les prompts et les réponses en local
- [ ] Utiliser un json pour créer des nouveaux menu et des prompts
- [ ] faire un mode text as input vs voice as input
- [ ] gérer le password pour le sudo
- [ ] mode conversation avec chatgpt
